/// Full ISO 3166-1 alpha-2 country list with localized names.
class CountryData {
  final String code;
  final String nameEn;
  final String nameRu;

  const CountryData(this.code, this.nameEn, this.nameRu);

  String name(String locale) => locale == 'ru' ? nameRu : nameEn;
}

const allCountries = <CountryData>[
  CountryData('AF', 'Afghanistan', 'Афганистан'),
  CountryData('AL', 'Albania', 'Албания'),
  CountryData('DZ', 'Algeria', 'Алжир'),
  CountryData('AD', 'Andorra', 'Андорра'),
  CountryData('AO', 'Angola', 'Ангола'),
  CountryData('AG', 'Antigua and Barbuda', 'Антигуа и Барбуда'),
  CountryData('AR', 'Argentina', 'Аргентина'),
  CountryData('AM', 'Armenia', 'Армения'),
  CountryData('AU', 'Australia', 'Австралия'),
  CountryData('AT', 'Austria', 'Австрия'),
  CountryData('AZ', 'Azerbaijan', 'Азербайджан'),
  CountryData('BS', 'Bahamas', 'Багамы'),
  CountryData('BH', 'Bahrain', 'Бахрейн'),
  CountryData('BD', 'Bangladesh', 'Бангладеш'),
  CountryData('BB', 'Barbados', 'Барбадос'),
  CountryData('BY', 'Belarus', 'Беларусь'),
  CountryData('BE', 'Belgium', 'Бельгия'),
  CountryData('BZ', 'Belize', 'Белиз'),
  CountryData('BJ', 'Benin', 'Бенин'),
  CountryData('BT', 'Bhutan', 'Бутан'),
  CountryData('BO', 'Bolivia', 'Боливия'),
  CountryData('BA', 'Bosnia and Herzegovina', 'Босния и Герцеговина'),
  CountryData('BW', 'Botswana', 'Ботсвана'),
  CountryData('BR', 'Brazil', 'Бразилия'),
  CountryData('BN', 'Brunei', 'Бруней'),
  CountryData('BG', 'Bulgaria', 'Болгария'),
  CountryData('BF', 'Burkina Faso', 'Буркина-Фасо'),
  CountryData('BI', 'Burundi', 'Бурунди'),
  CountryData('CV', 'Cabo Verde', 'Кабо-Верде'),
  CountryData('KH', 'Cambodia', 'Камбоджа'),
  CountryData('CM', 'Cameroon', 'Камерун'),
  CountryData('CA', 'Canada', 'Канада'),
  CountryData('CF', 'Central African Republic', 'ЦАР'),
  CountryData('TD', 'Chad', 'Чад'),
  CountryData('CL', 'Chile', 'Чили'),
  CountryData('CN', 'China', 'Китай'),
  CountryData('CO', 'Colombia', 'Колумбия'),
  CountryData('KM', 'Comoros', 'Коморы'),
  CountryData('CG', 'Congo', 'Конго'),
  CountryData('CD', 'Congo (DRC)', 'ДР Конго'),
  CountryData('CR', 'Costa Rica', 'Коста-Рика'),
  CountryData('CI', "Côte d'Ivoire", 'Кот-д\'Ивуар'),
  CountryData('HR', 'Croatia', 'Хорватия'),
  CountryData('CU', 'Cuba', 'Куба'),
  CountryData('CY', 'Cyprus', 'Кипр'),
  CountryData('CZ', 'Czechia', 'Чехия'),
  CountryData('DK', 'Denmark', 'Дания'),
  CountryData('DJ', 'Djibouti', 'Джибути'),
  CountryData('DM', 'Dominica', 'Доминика'),
  CountryData('DO', 'Dominican Republic', 'Доминиканская Республика'),
  CountryData('EC', 'Ecuador', 'Эквадор'),
  CountryData('EG', 'Egypt', 'Египет'),
  CountryData('SV', 'El Salvador', 'Сальвадор'),
  CountryData('GQ', 'Equatorial Guinea', 'Экваториальная Гвинея'),
  CountryData('ER', 'Eritrea', 'Эритрея'),
  CountryData('EE', 'Estonia', 'Эстония'),
  CountryData('SZ', 'Eswatini', 'Эсватини'),
  CountryData('ET', 'Ethiopia', 'Эфиопия'),
  CountryData('FJ', 'Fiji', 'Фиджи'),
  CountryData('FI', 'Finland', 'Финляндия'),
  CountryData('FR', 'France', 'Франция'),
  CountryData('GA', 'Gabon', 'Габон'),
  CountryData('GM', 'Gambia', 'Гамбия'),
  CountryData('GE', 'Georgia', 'Грузия'),
  CountryData('DE', 'Germany', 'Германия'),
  CountryData('GH', 'Ghana', 'Гана'),
  CountryData('GR', 'Greece', 'Греция'),
  CountryData('GD', 'Grenada', 'Гренада'),
  CountryData('GT', 'Guatemala', 'Гватемала'),
  CountryData('GN', 'Guinea', 'Гвинея'),
  CountryData('GW', 'Guinea-Bissau', 'Гвинея-Бисау'),
  CountryData('GY', 'Guyana', 'Гайана'),
  CountryData('HT', 'Haiti', 'Гаити'),
  CountryData('HN', 'Honduras', 'Гондурас'),
  CountryData('HU', 'Hungary', 'Венгрия'),
  CountryData('IS', 'Iceland', 'Исландия'),
  CountryData('IN', 'India', 'Индия'),
  CountryData('ID', 'Indonesia', 'Индонезия'),
  CountryData('IR', 'Iran', 'Иран'),
  CountryData('IQ', 'Iraq', 'Ирак'),
  CountryData('IE', 'Ireland', 'Ирландия'),
  CountryData('IL', 'Israel', 'Израиль'),
  CountryData('IT', 'Italy', 'Италия'),
  CountryData('JM', 'Jamaica', 'Ямайка'),
  CountryData('JP', 'Japan', 'Япония'),
  CountryData('JO', 'Jordan', 'Иордания'),
  CountryData('KZ', 'Kazakhstan', 'Казахстан'),
  CountryData('KE', 'Kenya', 'Кения'),
  CountryData('KI', 'Kiribati', 'Кирибати'),
  CountryData('KP', 'North Korea', 'КНДР'),
  CountryData('KR', 'South Korea', 'Южная Корея'),
  CountryData('KW', 'Kuwait', 'Кувейт'),
  CountryData('KG', 'Kyrgyzstan', 'Киргизия'),
  CountryData('LA', 'Laos', 'Лаос'),
  CountryData('LV', 'Latvia', 'Латвия'),
  CountryData('LB', 'Lebanon', 'Ливан'),
  CountryData('LS', 'Lesotho', 'Лесото'),
  CountryData('LR', 'Liberia', 'Либерия'),
  CountryData('LY', 'Libya', 'Ливия'),
  CountryData('LI', 'Liechtenstein', 'Лихтенштейн'),
  CountryData('LT', 'Lithuania', 'Литва'),
  CountryData('LU', 'Luxembourg', 'Люксембург'),
  CountryData('MG', 'Madagascar', 'Мадагаскар'),
  CountryData('MW', 'Malawi', 'Малави'),
  CountryData('MY', 'Malaysia', 'Малайзия'),
  CountryData('MV', 'Maldives', 'Мальдивы'),
  CountryData('ML', 'Mali', 'Мали'),
  CountryData('MT', 'Malta', 'Мальта'),
  CountryData('MH', 'Marshall Islands', 'Маршалловы Острова'),
  CountryData('MR', 'Mauritania', 'Мавритания'),
  CountryData('MU', 'Mauritius', 'Маврикий'),
  CountryData('MX', 'Mexico', 'Мексика'),
  CountryData('FM', 'Micronesia', 'Микронезия'),
  CountryData('MD', 'Moldova', 'Молдова'),
  CountryData('MC', 'Monaco', 'Монако'),
  CountryData('MN', 'Mongolia', 'Монголия'),
  CountryData('ME', 'Montenegro', 'Черногория'),
  CountryData('MA', 'Morocco', 'Марокко'),
  CountryData('MZ', 'Mozambique', 'Мозамбик'),
  CountryData('MM', 'Myanmar', 'Мьянма'),
  CountryData('NA', 'Namibia', 'Намибия'),
  CountryData('NR', 'Nauru', 'Науру'),
  CountryData('NP', 'Nepal', 'Непал'),
  CountryData('NL', 'Netherlands', 'Нидерланды'),
  CountryData('NZ', 'New Zealand', 'Новая Зеландия'),
  CountryData('NI', 'Nicaragua', 'Никарагуа'),
  CountryData('NE', 'Niger', 'Нигер'),
  CountryData('NG', 'Nigeria', 'Нигерия'),
  CountryData('MK', 'North Macedonia', 'Северная Македония'),
  CountryData('NO', 'Norway', 'Норвегия'),
  CountryData('OM', 'Oman', 'Оман'),
  CountryData('PK', 'Pakistan', 'Пакистан'),
  CountryData('PW', 'Palau', 'Палау'),
  CountryData('PS', 'Palestine', 'Палестина'),
  CountryData('PA', 'Panama', 'Панама'),
  CountryData('PG', 'Papua New Guinea', 'Папуа — Новая Гвинея'),
  CountryData('PY', 'Paraguay', 'Парагвай'),
  CountryData('PE', 'Peru', 'Перу'),
  CountryData('PH', 'Philippines', 'Филиппины'),
  CountryData('PL', 'Poland', 'Польша'),
  CountryData('PT', 'Portugal', 'Португалия'),
  CountryData('QA', 'Qatar', 'Катар'),
  CountryData('RO', 'Romania', 'Румыния'),
  CountryData('RU', 'Russia', 'Россия'),
  CountryData('RW', 'Rwanda', 'Руанда'),
  CountryData('KN', 'Saint Kitts and Nevis', 'Сент-Китс и Невис'),
  CountryData('LC', 'Saint Lucia', 'Сент-Люсия'),
  CountryData('VC', 'Saint Vincent', 'Сент-Винсент и Гренадины'),
  CountryData('WS', 'Samoa', 'Самоа'),
  CountryData('SM', 'San Marino', 'Сан-Марино'),
  CountryData('ST', 'São Tomé and Príncipe', 'Сан-Томе и Принсипи'),
  CountryData('SA', 'Saudi Arabia', 'Саудовская Аравия'),
  CountryData('SN', 'Senegal', 'Сенегал'),
  CountryData('RS', 'Serbia', 'Сербия'),
  CountryData('SC', 'Seychelles', 'Сейшелы'),
  CountryData('SL', 'Sierra Leone', 'Сьерра-Леоне'),
  CountryData('SG', 'Singapore', 'Сингапур'),
  CountryData('SK', 'Slovakia', 'Словакия'),
  CountryData('SI', 'Slovenia', 'Словения'),
  CountryData('SB', 'Solomon Islands', 'Соломоновы Острова'),
  CountryData('SO', 'Somalia', 'Сомали'),
  CountryData('ZA', 'South Africa', 'ЮАР'),
  CountryData('SS', 'South Sudan', 'Южный Судан'),
  CountryData('ES', 'Spain', 'Испания'),
  CountryData('LK', 'Sri Lanka', 'Шри-Ланка'),
  CountryData('SD', 'Sudan', 'Судан'),
  CountryData('SR', 'Suriname', 'Суринам'),
  CountryData('SE', 'Sweden', 'Швеция'),
  CountryData('CH', 'Switzerland', 'Швейцария'),
  CountryData('SY', 'Syria', 'Сирия'),
  CountryData('TW', 'Taiwan', 'Тайвань'),
  CountryData('TJ', 'Tajikistan', 'Таджикистан'),
  CountryData('TZ', 'Tanzania', 'Танзания'),
  CountryData('TH', 'Thailand', 'Таиланд'),
  CountryData('TL', 'Timor-Leste', 'Восточный Тимор'),
  CountryData('TG', 'Togo', 'Того'),
  CountryData('TO', 'Tonga', 'Тонга'),
  CountryData('TT', 'Trinidad and Tobago', 'Тринидад и Тобаго'),
  CountryData('TN', 'Tunisia', 'Тунис'),
  CountryData('TR', 'Turkey', 'Турция'),
  CountryData('TM', 'Turkmenistan', 'Туркменистан'),
  CountryData('TV', 'Tuvalu', 'Тувалу'),
  CountryData('UG', 'Uganda', 'Уганда'),
  CountryData('UA', 'Ukraine', 'Украина'),
  CountryData('AE', 'United Arab Emirates', 'ОАЭ'),
  CountryData('GB', 'United Kingdom', 'Великобритания'),
  CountryData('US', 'United States', 'США'),
  CountryData('UY', 'Uruguay', 'Уругвай'),
  CountryData('UZ', 'Uzbekistan', 'Узбекистан'),
  CountryData('VU', 'Vanuatu', 'Вануату'),
  CountryData('VA', 'Vatican City', 'Ватикан'),
  CountryData('VE', 'Venezuela', 'Венесуэла'),
  CountryData('VN', 'Vietnam', 'Вьетнам'),
  CountryData('YE', 'Yemen', 'Йемен'),
  CountryData('ZM', 'Zambia', 'Замбия'),
  CountryData('ZW', 'Zimbabwe', 'Зимбабве'),
];

/// Find country name by code and locale.
String? countryName(String? code, String locale) {
  if (code == null) return null;
  final upper = code.toUpperCase();
  for (final c in allCountries) {
    if (c.code == upper) return c.name(locale);
  }
  return code; // fallback to code if not found
}
